### ISSUE TITLE
Is mandatory to use app name with url ?

### ISSUE THREAD

**Issue by DTSREPO** [SabujXi/SKFCMS#2]
File : **category_form.html**
LIne : _{% url 'ecom_app:cat_form' cat.id %}_
Issue : **ecom_app:cat_form**
Is mandatory to use app name (**ecom_app**) with url ?

**Comment by kamruljpi** [comment]
not mandatory to use app name when you generate a URL. but its a good practice for a programmer. 
its not a app name Its called namespace . if you want to use namespace then you should have to need assign namespace when you will include a app urls to your project urls.  also you can avoid the namespace but its not good practice. 

I think the answer is correct but @SabujXi vai can be explain with more details. I have said which i have understood from @SabujXi vai.

**Comment by DTSREPO** [comment]
Thanks @kamruljpi you are right.
If use namespace then namespace **ecom_app:cat_form** is mandatory to use in url.
