### ISSUE TITLE
Add new menu problem when database table (Menu) null

### ISSUE THREAD

**Issue by DTSREPO** [SabujXi/SKFCMS#5]
Add new menu problem when database table (Menu) null.
i have clone this repository and migrate it with make migrations but when i try create menu then display an error @kamruljpi  or @SabujXi you may check it

**Comment by SabujXi** [comment]
Please specify the URL and/or the stack trace @rubelnl

**Comment by SabujXi** [comment]
There was a problem in logical operation.
We used `if parent != "-1" or parent != ""` instead of `if parent != "-1" and parent != ""`  that resulted in execution of wrong block  of code.
